### ISSUE TITLE
Traceback Due To Refferences to a Dropbox File

### ISSUE THREAD

**Issue by ntcarver** [mltony/nvda-tonys-enhancements#1]
NVDA debug log:

DEBUG - __main__ (21:06:07.143) - MainThread (4452):
Provided arguments: ['C:\\Program Files (x86)\\NVDA\\nvda.exe', 'C:\\Program Files (x86)\\NVDA\\nvda.exe', 'C:\\Program Files (x86)\\NVDA\\nvda.exe', 'C:\\Program Files (x86)\\NVDA\\nvda.exe', 'C:\\Program Files (x86)\\NVDA\\nvda.exe', 'C:\\Program Files (x86)\\NVDA\\nvda.exe', 'C:\\Program Files (x86)\\NVDA\\nvda.exe', 'C:\\Program Files (x86)\\NVDA\\nvda.exe', 'C:\\Program Files (x86)\\NVDA\\nvda.exe', 'C:\\Program Files (x86)\\NVDA\\nvda.exe', '--debug-logging']
INFO - __main__ (21:06:07.143) - MainThread (4452):
Starting NVDA version 2019.3beta2
DEBUG - __main__ (21:06:07.143) - MainThread (4452):
Debug level logging enabled
DEBUG - core.main (21:06:07.419) - MainThread (4452):
Core starting
INFO - core.main (21:06:07.421) - MainThread (4452):
Config dir: C:\Users\noahc\AppData\Roaming\nvda
DEBUG - core.main (21:06:07.422) - MainThread (4452):
loading config
INFO - config.ConfigManager._loadConfig (21:06:07.422) - MainThread (4452):
Loading config: C:\Users\noahc\AppData\Roaming\nvda\nvda.ini
DEBUG - config.profileUpgrader.upgrade (21:06:07.426) - MainThread (4452):
Current config schema version: 3, latest: 3
DEBUG - fileUtils.FaultTolerantFile (21:06:07.433) - MainThread (4452):
C:\Users\noahc\AppData\Roaming\nvda\nvda.iniclq1tehy.tmp
INFO - config.ConfigManager._loadConfig (21:06:07.439) - MainThread (4452):
Config loaded (after upgrade, and in the state it will be used by NVDA):
{'schemaVersion': '3', 'update': {'autoCheck': 'True', 'startupNotification': 'True', 'allowUsageStats': 'True', 'askedAllowUsageStats': 'True'}, 'upgrade': {}, 'general': {'language': 'Windows', 'saveConfigurationOnExit': 'True', 'askToExit': 'True', 'playStartAndExitSounds': 'True', 'loggingLevel': 'INFO', 'showWelcomeDialogAtStartup': 'False'}, 'development': {}, 'speech': {'synth': 'espeak', 'outputDevice': 'Microsoft Sound Mapper', 'autoLanguageSwitching': 'False', 'symbolLevel': '200', 'oneCore': {'voice': 'HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Speech_OneCore\\Voices\\Tokens\\MSTTS_V110_enUS_DavidM', 'volume': '100'}, 'espeak': {'voice': 'en-us', 'variant': 'max', 'rate': '45', 'pitch': '51', 'inflection': '51', 'volume': '100', 'rateBoost': 'True', 'capPitchChange': '50'}}, 'braille': {'noBraille': {}}, 'vision': {'NVDAHighlighter': {'highlightFocus': 'False', 'highlightNavigator': 'False', 'highlightBrowseMode': 'False'}, 'screenCurtain': {'warnOnLoad': 'False', 'enabled': 'True'}}, 'keyboard': {'useCapsLockAsNVDAModifierKey': 'True', 'speakTypedCharacters': 'False', 'keyboardLayout': 'desktop'}, 'uwpOcr': {'language': 'en-US'}, 'audio': {'audioDuckingMode': '0'}, 'presentation': {'progressBarUpdates': {'progressBarOutputMode': 'beep'}}, 'documentFormatting': {'autoLanguageSwitching': 'False'}}
DEBUG - core.main (21:06:07.494) - MainThread (4452):
setting language to Windows
INFO - core.main (21:06:07.494) - MainThread (4452):
Using Windows version 10.0.18363 workstation
INFO - core.main (21:06:07.494) - MainThread (4452):
Using Python version 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 14 2019, 23:09:19) [MSC v.1916 32 bit (Intel)]
INFO - core.main (21:06:07.494) - MainThread (4452):
Using comtypes version 1.1.7
INFO - core.main (21:06:07.495) - MainThread (4452):
Using configobj version 5.1.0 with validate version 1.0.1
DEBUG - core.main (21:06:07.501) - MainThread (4452):
Initializing add-ons system
DEBUG - addonHandler._getAvailableAddonsFromPath (21:06:07.501) - MainThread (4452):
Listing add-ons from C:\Users\noahc\AppData\Roaming\nvda\addons
DEBUG - addonHandler._getAvailableAddonsFromPath (21:06:07.502) - MainThread (4452):
Loading add-on from C:\Users\noahc\AppData\Roaming\nvda\addons\addonUpdater
DEBUG - addonHandler._getAvailableAddonsFromPath (21:06:07.503) - MainThread (4452):
Found add-on addonUpdater - 20.01.1. Requires API: (2019, 2, 0). Last-tested API: (2019, 3, 0)
DEBUG - addonHandler._getAvailableAddonsFromPath (21:06:07.503) - MainThread (4452):
Loading add-on from C:\Users\noahc\AppData\Roaming\nvda\addons\audioChart
DEBUG - addonHandler._getAvailableAddonsFromPath (21:06:07.503) - MainThread (4452):
Found add-on audioChart - 1.2. Requires API: (2019, 2, 0). Last-tested API: (2019, 3, 0)
DEBUG - addonHandler._getAvailableAddonsFromPath (21:06:07.504) - MainThread (4452):
Loading add-on from C:\Users\noahc\AppData\Roaming\nvda\addons\browsernav
DEBUG - addonHandler._getAvailableAddonsFromPath (21:06:07.505) - MainThread (4452):
Found add-on browsernav - 1.9. Requires API: (2019, 3, 0). Last-tested API: (2019, 3, 0)
DEBUG - addonHandler._getAvailableAddonsFromPath (21:06:07.505) - MainThread (4452):
Loading add-on from C:\Users\noahc\AppData\Roaming\nvda\addons\dayOfTheWeek
DEBUG - addonHandler._getAvailableAddonsFromPath (21:06:07.506) - MainThread (4452):
Found add-on dayOfTheWeek - 19.12. Requires API: (2014, 3, 0). Last-tested API: (2019, 4, 0)
DEBUG - addonHandler._getAvailableAddonsFromPath (21:06:07.506) - MainThread (4452):
Loading add-on from C:\Users\noahc\AppData\Roaming\nvda\addons\IndentNav
DEBUG - addonHandler._getAvailableAddonsFromPath (21:06:07.507) - MainThread (4452):
Found add-on IndentNav - 1.10. Requires API: (2019, 2, 0). Last-tested API: (2019, 3, 0)
DEBUG - addonHandler._getAvailableAddonsFromPath (21:06:07.507) - MainThread (4452):
Loading add-on from C:\Users\noahc\AppData\Roaming\nvda\addons\Mozilla
DEBUG - addonHandler._getAvailableAddonsFromPath (21:06:07.508) - MainThread (4452):
Found add-on Mozilla - 1.9.2. Requires API: (2018, 1, 0). Last-tested API: (2019, 3, 0)
DEBUG - addonHandler._getAvailableAddonsFromPath (21:06:07.509) - MainThread (4452):
Loading add-on from C:\Users\noahc\AppData\Roaming\nvda\addons\resourceMonitor
DEBUG - addonHandler._getAvailableAddonsFromPath (21:06:07.509) - MainThread (4452):
Found add-on resourceMonitor - 20.01. Requires API: (2019, 3, 0). Last-tested API: (2019, 3, 0)
DEBUG - addonHandler._getAvailableAddonsFromPath (21:06:07.510) - MainThread (4452):
Loading add-on from C:\Users\noahc\AppData\Roaming\nvda\addons\textnav
DEBUG - addonHandler._getAvailableAddonsFromPath (21:06:07.510) - MainThread (4452):
Found add-on textnav - 1.4. Requires API: (2019, 2, 0). Last-tested API: (2019, 3, 0)
DEBUG - addonHandler._getAvailableAddonsFromPath (21:06:07.510) - MainThread (4452):
Loading add-on from C:\Users\noahc\AppData\Roaming\nvda\addons\tonysEnhancements
DEBUG - addonHandler._getAvailableAddonsFromPath (21:06:07.511) - MainThread (4452):
Found add-on tonysEnhancements - 1.3. Requires API: (2019, 3, 0). Last-tested API: (2019, 3, 0)
DEBUG - addonHandler._getAvailableAddonsFromPath (21:06:07.511) - MainThread (4452):
Loading add-on from C:\Users\noahc\AppData\Roaming\nvda\addons\toolbarsExplorer
DEBUG - addonHandler._getAvailableAddonsFromPath (21:06:07.512) - MainThread (4452):
Found add-on toolbarsExplorer - 1.4. Requires API: (2017, 3, 0). Last-tested API: (2019, 3, 0)
DEBUG - addonHandler._getAvailableAddonsFromPath (21:06:07.513) - MainThread (4452):
Loading add-on from C:\Users\noahc\AppData\Roaming\nvda\addons\wintenApps
DEBUG - addonHandler._getAvailableAddonsFromPath (21:06:07.513) - MainThread (4452):
Found add-on wintenApps - 20.01. Requires API: (2019, 3, 0). Last-tested API: (2019, 3, 0)
DEBUGWARNING - touchHandler.touchSupported (21:06:07.639) - MainThread (4452):
No touch devices found
DEBUG - core.main (21:06:07.736) - MainThread (4452):
Initializing appModule Handler
DEBUG - addonHandler.Addon.addToPackagePath (21:06:07.737) - MainThread (4452):
Addon Mozilla added to appModules package path
DEBUG - addonHandler.Addon.addToPackagePath (21:06:07.737) - MainThread (4452):
Addon wintenApps added to appModules package path
DEBUG - core.main (21:06:07.738) - MainThread (4452):
Initializing NVDAHelper
DEBUG - core.main (21:06:07.785) - MainThread (4452):
Initializing tones
DEBUG - core.main (21:06:07.792) - MainThread (4452):
Speech Dictionary processing
DEBUG - speechDictHandler.SpeechDict.load (21:06:07.792) - MainThread (4452):
Loading speech dictionary 'C:\Users\noahc\AppData\Roaming\nvda\speechDicts\default.dic'...
DEBUG - speechDictHandler.SpeechDict.load (21:06:07.792) - MainThread (4452):
file 'C:\Users\noahc\AppData\Roaming\nvda\speechDicts\default.dic' not found.
DEBUG - speechDictHandler.SpeechDict.load (21:06:07.792) - MainThread (4452):
Loading speech dictionary 'builtin.dic'...
DEBUG - speechDictHandler.SpeechDict.load (21:06:07.794) - MainThread (4452):
3 loaded records.
DEBUG - core.main (21:06:07.794) - MainThread (4452):
Initializing speech
INFO - synthDrivers.espeak.SynthDriver.__init__ (21:06:07.828) - MainThread (4452):
Using eSpeak NG version b'1.49.3 dev'
DEBUG - speechDictHandler.SpeechDict.load (21:06:07.900) - MainThread (4452):
Loading speech dictionary 'C:\Users\noahc\AppData\Roaming\nvda\speechDicts\voiceDicts.v1\espeak\espeak-English (America).dic'...
DEBUG - speechDictHandler.SpeechDict.load (21:06:07.901) - MainThread (4452):
file 'C:\Users\noahc\AppData\Roaming\nvda\speechDicts\voiceDicts.v1\espeak\espeak-English (America).dic' not found.
DEBUG - synthDriverHandler.SynthDriver.loadSettings (21:06:07.902) - MainThread (4452):
Loaded settings for SynthDriver espeak
INFO - synthDriverHandler.setSynth (21:06:07.902) - MainThread (4452):
Loaded synthDriver espeak
INFO - core.main (21:06:07.902) - MainThread (4452):
Using wx version 4.0.3 msw (phoenix) wxWidgets 3.0.5 with six version 1.12.0
DEBUG - core.main (21:06:07.903) - MainThread (4452):
Initializing braille input
INFO - brailleInput.initialize (21:06:07.903) - MainThread (4452):
Braille input initialized
DEBUG - core.main (21:06:07.904) - MainThread (4452):
Initializing braille
INFO - braille.initialize (21:06:07.904) - MainThread (4452):
Using liblouis version 3.10.0
INFO - braille.initialize (21:06:07.907) - MainThread (4452):
Using pySerial version 3.4
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._registerConfigSaveAction (21:06:07.908) - MainThread (4452):
registering pre_configSave action: <class 'brailleDisplayDrivers.noBraille.BrailleDisplayDriver'>
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._loadSpecificSettings (21:06:07.912) - MainThread (4452):
loading braille noBraille
INFO - braille.BrailleHandler.setDisplayByName (21:06:07.912) - MainThread (4452):
Loaded braille display driver noBraille, current display has 0 cells.
DEBUG - core.main (21:06:07.912) - MainThread (4452):
Initializing vision
DEBUG - core.main (21:06:07.913) - MainThread (4452):
Initializing displayModel
DEBUG - core.main (21:06:07.913) - MainThread (4452):
Initializing GUI
DEBUG - windowUtils._rawWindowProc (21:06:07.939) - MainThread (4452):
CustomWindow rawWindowProc called for unknown window 1245848
DEBUG - windowUtils._rawWindowProc (21:06:07.939) - MainThread (4452):
CustomWindow rawWindowProc called for unknown window 1245848
DEBUG - windowUtils._rawWindowProc (21:06:07.940) - MainThread (4452):
CustomWindow rawWindowProc called for unknown window 1245848
DEBUG - windowUtils._rawWindowProc (21:06:07.940) - MainThread (4452):
CustomWindow rawWindowProc called for unknown window 1245848
DEBUG - core.main (21:06:07.945) - MainThread (4452):
initializing Java Access Bridge support
INFO - core.main (21:06:08.090) - MainThread (4452):
Java Access Bridge support initialized
DEBUG - core.main (21:06:08.092) - MainThread (4452):
Initializing legacy winConsole support
DEBUG - core.main (21:06:08.092) - MainThread (4452):
Initializing UIA support
INFO - _UIAHandler.UIAHandler.MTAThreadFunc (21:06:08.105) - _UIAHandler.UIAHandler.MTAThread (3572):
UIAutomation: IUIAutomation6
DEBUG - core.main (21:06:08.253) - MainThread (4452):
Initializing IAccessible support
DEBUG - core.main (21:06:08.253) - MainThread (4452):
Initializing input core
DEBUGWARNING - inputCore.InputManager.loadLocaleGestureMap (21:06:08.254) - MainThread (4452):
No locale gesture map for language en
DEBUG - core.main (21:06:08.254) - MainThread (4452):
Initializing keyboard handler
DEBUG - core.main (21:06:08.255) - MainThread (4452):
initializing mouse handler
DEBUG - core.main (21:06:08.285) - MainThread (4452):
Initializing touchHandler
DEBUGWARNING - touchHandler.touchSupported (21:06:08.286) - MainThread (4452):
No touch devices found
DEBUG - core.main (21:06:08.286) - MainThread (4452):
Initializing global plugin handler
DEBUG - addonHandler.Addon.addToPackagePath (21:06:08.286) - MainThread (4452):
Addon addonUpdater added to globalPlugins package path
DEBUG - addonHandler.Addon.addToPackagePath (21:06:08.286) - MainThread (4452):
Addon audioChart added to globalPlugins package path
DEBUG - addonHandler.Addon.addToPackagePath (21:06:08.286) - MainThread (4452):
Addon browsernav added to globalPlugins package path
DEBUG - addonHandler.Addon.addToPackagePath (21:06:08.287) - MainThread (4452):
Addon dayOfTheWeek added to globalPlugins package path
DEBUG - addonHandler.Addon.addToPackagePath (21:06:08.287) - MainThread (4452):
Addon IndentNav added to globalPlugins package path
DEBUG - addonHandler.Addon.addToPackagePath (21:06:08.287) - MainThread (4452):
Addon resourceMonitor added to globalPlugins package path
DEBUG - addonHandler.Addon.addToPackagePath (21:06:08.287) - MainThread (4452):
Addon textnav added to globalPlugins package path
DEBUG - addonHandler.Addon.addToPackagePath (21:06:08.287) - MainThread (4452):
Addon tonysEnhancements added to globalPlugins package path
DEBUG - addonHandler.Addon.addToPackagePath (21:06:08.287) - MainThread (4452):
Addon toolbarsExplorer added to globalPlugins package path
DEBUG - addonHandler.Addon.addToPackagePath (21:06:08.288) - MainThread (4452):
Addon wintenApps added to globalPlugins package path
DEBUG - external:globalPlugins.wintenObjs.GlobalPlugin.__init__ (21:06:08.290) - MainThread (4452):
W10: adding additional events
DEBUG - external:globalPlugins.wintenObjs.GlobalPlugin.__init__ (21:06:08.297) - MainThread (4452):
W10: added event ID 20026, assigned to UIA_dragStart
DEBUG - external:globalPlugins.wintenObjs.GlobalPlugin.__init__ (21:06:08.303) - MainThread (4452):
W10: added event ID 20027, assigned to UIA_dragCancel
DEBUG - external:globalPlugins.wintenObjs.GlobalPlugin.__init__ (21:06:08.308) - MainThread (4452):
W10: added event ID 20028, assigned to UIA_dragComplete
DEBUG - external:globalPlugins.wintenObjs.GlobalPlugin.__init__ (21:06:08.314) - MainThread (4452):
W10: added event ID 20029, assigned to UIA_dragEnter
DEBUG - external:globalPlugins.wintenObjs.GlobalPlugin.__init__ (21:06:08.319) - MainThread (4452):
W10: added event ID 20030, assigned to UIA_dragLeave
DEBUG - external:globalPlugins.wintenObjs.GlobalPlugin.__init__ (21:06:08.325) - MainThread (4452):
W10: added event ID 20031, assigned to UIA_dragDropped
DEBUG - external:globalPlugins.wintenObjs.GlobalPlugin.__init__ (21:06:08.325) - MainThread (4452):
W10: adding class name Popup to known dialog class names
ERROR - globalPluginHandler.listPlugins (21:06:08.340) - MainThread (4452):
Error importing global plugin tonysEnhancements
Traceback (most recent call last):
  File "globalPluginHandler.pyc", line 23, in listPlugins
  File "importlib\__init__.pyc", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\noahc\AppData\Roaming\nvda\addons\tonysEnhancements\globalPlugins\tonysEnhancements.py", line 50, in <module>
    f = open("C:\\Users\\tony\\Dropbox\\2.txt", "w")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\tony\\Dropbox\\2.txt'
DEBUG - core.main (21:06:08.389) - MainThread (4452):
Initializing core pump
DEBUG - core.main (21:06:08.390) - MainThread (4452):
Initializing watchdog
DEBUG - core.main (21:06:08.390) - MainThread (4452):
initializing updateCheck
INFO - core.main (21:06:08.391) - MainThread (4452):
NVDA initialized
DEBUG - core.main (21:06:08.391) - MainThread (4452):
entering wx application main loop
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._registerConfigSaveAction (21:06:08.396) - MainThread (4452):
registering pre_configSave action: <class 'visionEnhancementProviders.NVDAHighlighter.NVDAHighlighterSettings'>
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._loadSpecificSettings (21:06:08.400) - MainThread (4452):
loading vision NVDAHighlighter
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._loadSpecificSettings (21:06:08.400) - MainThread (4452):
Loaded settings for NVDAHighlighterSettings
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._registerConfigSaveAction (21:06:08.404) - MainThread (4452):
registering pre_configSave action: <class 'visionEnhancementProviders.screenCurtain.ScreenCurtainSettings'>
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._loadSpecificSettings (21:06:08.409) - MainThread (4452):
loading vision screenCurtain
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._loadSpecificSettings (21:06:08.410) - MainThread (4452):
Loaded settings for ScreenCurtainSettings
DEBUG - visionEnhancementProviders.screenCurtain.ScreenCurtainProvider.__init__ (21:06:08.410) - MainThread (4452):
Starting ScreenCurtain
IO - speech.speak (21:06:08.434) - MainThread (4452):
Speaking ['Untitled - Notepad']
DEBUGWARNING - characterProcessing._getSpeechSymbolsForLocale (21:06:08.435) - MainThread (4452):
No CLDR data for locale en_US
IO - speech.speak (21:06:08.522) - MainThread (4452):
Speaking ['Text Editor', 'edit', 'multi line']
DEBUG - NVDAObjects.NVDAObject._get_placeholder (21:06:08.525) - MainThread (4452):
Potential unimplemented child class: <NVDAObjects.Dynamic_IAccessibleEditWindowNVDAObjectEditableIndentNav object at 0x04086D90>
IO - speech.speak (21:06:08.526) - MainThread (4452):
Speaking ['blank']
IO - inputCore.InputManager.executeGesture (21:06:10.358) - winInputHook (6572):
Input: kb(desktop):NVDA+n
IO - speech.speak (21:06:10.439) - MainThread (4452):
Speaking ['NVDA', 'menu']
IO - inputCore.InputManager.executeGesture (21:06:11.631) - winInputHook (6572):
Input: kb(desktop):downArrow
IO - speech.speak (21:06:11.649) - MainThread (4452):
Speaking ['Preferences', 'subMenu', 'p']
IO - inputCore.InputManager.executeGesture (21:06:12.387) - winInputHook (6572):
Input: kb(desktop):downArrow
IO - speech.speak (21:06:12.401) - MainThread (4452):
Speaking ['Tools', 'subMenu', 't']
IO - inputCore.InputManager.executeGesture (21:06:13.126) - winInputHook (6572):
Input: kb(desktop):enter
IO - speech.speak (21:06:13.153) - MainThread (4452):
Speaking ['View log', 'v']
IO - inputCore.InputManager.executeGesture (21:06:13.821) - winInputHook (6572):
Input: kb(desktop):enter

**Comment by trypsynth** [comment]
This seems to only happen when the debug flag is set. Are you running with the latest version of the addon?

**Comment by cary-rowen** [comment]
It cannot be reproduced. Close this.
