### ISSUE TITLE
NVDA+Delete conflicts with laptop layout

### ISSUE THREAD

**Issue by tmthywynn8** [mltony/nvda-tonys-enhancements#10]
With version 1.14 of this add-on, the Toggle microphone mute gesture (NVDA+Delete ) conflicts with the laptop layout which is set to "Report review cursor location" bye default. The command can be found by going to NVDA menu>Help>Commands Quick Reference. Under the "Object Navigation" level-2 heading, you will find the conflicting gesture.

**Comment by cary-rowen** [comment]
Hi,
Would it work if I changed it to NVDA+Alt+Delete?
Thanks

**Comment by cary-rowen** [comment]
This feature is currently removed from the add-on and will be merged into NVDA2024.3, so close this issue.

**Comment by mltony** [comment]
Are you sure about that? I didn't remove mute microphone from the add-on. Maybe you meant adjusting applications volume - that one is indeed under review with nvaccess, but I didn't add microphone mute to NVDA.

**Comment by cary-rowen** [comment]
I'm so sorry, it was my mistake.
@mltony 
Can you suggest a new shortcut key for us to solve this issue?
BTW, we should limit the compatibility to 2024.2 because the pycaw module does not exist in 2024.1.

**Comment by mltony** [comment]
I don't know much about laptop layout, perhaps leave it unassigned? In the end there are fewer keys to work with in the laptop layout.
Limiting compatibility sounds good.

**Comment by cary-rowen** [comment]
@mltony 
I removed the default gestures and updated the doc.
