### ISSUE TITLE
Keyboard conflicts with laptop layout.

### ISSUE THREAD

**Issue by trypsynth** [mltony/nvda-tonys-enhancements#11]
Many of the keys (NVDA+Shift+Right arrow, control+NVDA+shift+right arrow, control+nvda+shift+down arrow, etc) all conflict with the laptop keyboard layout.

**Comment by RDMurray** [comment]
I just disable the conflicting keys, but it would be great if this addon didn't conflict with the laptop layout. I don't know the best place to assign them in the laptop layout, but perhaps a temporary fix would be to only assign the conflicting keys in the desktop layout.

**Comment by cary-rowen** [comment]
Hi @TheQuinbox 
Thanks for your feedback, These conflicting keystrokes no longer exist in add-ons as the related functionality has been merged into NVDA core.
Let's close this.
