### ISSUE TITLE
Compatibility with NVDA 2022.2

### ISSUE THREAD

**Issue by CyrilleB79** [mltony/nvda-tonys-enhancements#13]
Hi @mltony 

NVDA 2022.2 (beta1 today) has seen great improvements for table navigation thanks to your contribution. Thank you very much.

To be compatible with this version could you the following modifications in the add-on??

### Gesture unmapping
At least unmap the default key binding for jumpTo(First/Last)(Row/Column) scripts in the add-on so that NVDA's scripts can be executed instead of the add-on's ones. People using older versions of NVDA can still map these scripts themselves; but some little bugs remain in case of merged cells whereas it has been fixed in NVDA.
Or better, if you make a version compatible with NVDA 2022.2 onwards one day, remove totally these scripts.

### Fix the issue of merged cells
For the table scripts remaining in the add-on's field, e.g. jump to 2nd row, fix the issue that occurs when the jump crosses a merged cell. That's probably the same type of fix than the ones done in NVDA.

Many thanks!

Cyrille

**Comment by CyrilleB79** [comment]
And also, even if I have unmapped the add-on's functions, the jump to start/end of row/column function of NVDA 2022.2beta1 do not work correctly in Word (with UIA) in case the current row/column contains a merged cell.
You should probably limit some function patching with NVDA 2022.2.

Thanks.

**Comment by CyrilleB79** [comment]
Update: The following scripts should also be unmapped for 2022.4 and beyond since they have landed in NVDA 2022.4 (currently in beta phase): read column/row from current cell/the beginning.

Also one more fixe regarding table navigation is included in NVDA: #14298. I do not know if this code is duplicated in this add-on. So to be checked.

**Comment by cary-rowen** [comment]
Hi, @CyrilleB79 

I noticed you mentioned several issues, some of which have been resolved as far as I know.
For table navigation commands already included in NVDA core, I marked them as deprecated in the documentation, rather than removing them outright, in case people who relied on this add-on for their functionality in the past couldn't find them.

Do you have any new ideas for this Issue? I also agree with removing the default keymap for jump cells.

Also, NVDA+Delete toggles microphone status, which conflicts with NVDA's own gesture, which seems like it should be fixed as well.
@mltony What do you recommend for these?

Thanks

**Comment by CyrilleB79** [comment]
> I noticed you mentioned several issues, some of which have been resolved as far as I know.

Well, there are still issues, specifically the one when crossing merged cells. But maybe it's better to open a specific issue with detailed STR.

> For table navigation commands already included in NVDA core, I marked them as deprecated in the documentation, rather than removing them outright, in case people who relied on this add-on for their functionality in the past couldn't find them.

But they are actually removed, not only deprecated, or are they?

> Do you have any new ideas for this Issue? I also agree with removing the default keymap for jump cells.

Maybe not in this issue.

> Also, NVDA+Delete toggles microphone status, which conflicts with NVDA's own gesture, which seems like it should be fixed as well. @mltony What do you recommend for these?

Should rather be discussed in #11.

**Comment by mltony** [comment]
Table commands to jump to first/last row/column have been added to NVDA 
core. Also Table SayAll commands. I would say we should drop them from 
this add-on to reduce the amount of dead code and mention in the doc 
that these commands have been graduated to NVDA core.

As for NVDA+Delete, Let's try to find another unused key combination - 
it's better than to override default NVDA shortcuts.

**Comment by CyrilleB79** [comment]
I have opened another issue describing with more details the "Fix the issue of merged cells": see #22.

Thus for me, the current issue can be closed.

**Comment by cary-rowen** [comment]
Thanks to @CyrilleB79 for clarifying this.
For deleted commands, I will mention it in the documentation as Tony said.
Can we use the NVDA+Alt+Delete combination for the ability to toggle the microphone?

**Comment by cary-rowen** [comment]
The mentioned issue has been described in more detail in #22, I will close this now.
