### ISSUE TITLE
No menu comes up when pressing nvda+alt+t in a table

### ISSUE THREAD

**Issue by frastlin** [mltony/nvda-tonys-enhancements#19]
Hello,
I just installed this addon in NVDA 2022.4 and when in a table and pressing NVDA+alt+t, nothing happens.
When I am not in a table and press nvda+alt+t, I hear "Not in a table!" so I know the key command is working.
Any ideas on how to fix this?
Thanks,

**Comment by cary-rowen** [comment]
has been fixed and will be included in the next stable release.
