### ISSUE TITLE
No voice when reloading add-ons

### ISSUE THREAD

**Issue by CyrilleB79** [mltony/nvda-tonys-enhancements#26]
Hi @cary-rowen and @mltony 

Thanks for the release 1.16. I have an issue with this however.

### Steps to reproduce
* Use a brand new NVDA with no add-on installed
* Install Tony's enhancements and restart as requested
* Reload the add-ons with NVDA+control+F3
### Actual result
When NVDA starts with the add-on installed, all is OK.
But after reloading the add-ons with NVDA+shift+F3, there is no speech anymore.

### Expected result
The add-ons can be reloaded and speech remains available.

### Log
[nvda-old.log](https://github.com/mltony/nvda-tonys-enhancements/files/12577031/nvda-old.log)

**Comment by maxe-hsieh** [comment]
Tony forgot to remove this code:
nvwave.WavePlayer.open = originalWaveOpen

**Comment by cary-rowen** [comment]
Thanks @maxe-hsieh and @CyrilleB79  for pointing this out, I fixed this while cleaning up some other unused imports and variables.
