### ISSUE TITLE
Where is the version compatible with NVDA 2024.1

### ISSUE THREAD

**Issue by marlon-sousa** [mltony/nvda-tonys-enhancements#27]
I see in the readme that the addon is compatible with NVDA 2024.1 but it does not appear in the nvda addon store.

I have tried to enable all the channels and still it is not available.

I see that in the releases no version of the addon is present after end of 2023.

So, my question is:

Is this addon already compatible to NVDA 2024.1?

If so, how can I download it?

P.S. this addon has enhanced my productivity in development activities, and I am waiting for its availability to update NVDA to 2024.x branches.

**Comment by mltony** [comment]
For now download from github releases page. Currently addon submission is broken in addon store - I'll try to submit again when it's fixed.

**Comment by marlon-sousa** [comment]
Ok,

It is working perfectly.

Closing this issue as of now, because the release version is available and works.
