### ISSUE TITLE
Japanese character set regexp?

### ISSUE THREAD

**Issue by zersiax** [mltony/nvda-tonys-enhancements#4]
Hello,

I see there is a character set for Chinese, as well as Russian, but I am missing one for Japanese. I know that Chinese and Japanese share a lot of characters according to UTF-8 so I will most likely have to remove the one for Chinese and add the Japanese one. However, I am having a bit of trouble getting the regexp right for all the three alphabets. My attempt:
ja_ja:([一-龯])

This gives us (most) kanji, and works for those. However, ideally, I would also like to add the following regexp:
([ぁ-んァ-ン])
which should add hiragana and katakana. However, adding that line below the previous one makes the entire thing not work anymore. My regexp is a bit rusty and I'm not sure how to combine these two. Am I reinventing the wheel here?

**Comment by mltony** [comment]
I don't speak either Chinese or Japanese, but yes, as far as I know they 
reuse the same Unicode characters, so you're right that you'd have to 
remove Chinese in order to be able to add Japanese.
I did a quick search and here is what I found:
https://gist.github.com/terrancesnyder/1345094
https://gist.github.com/ryanmcgrath/982242
Are these links helpful?


------ Original Message ------

**Comment by zersiax** [comment]
Somewhat :) hat first link, is where I got the first regexp from. Like I said, I think it will probably work, if  those two regular expressions can be combined somehow. I just don't know how to do that. Do you know how those two can be combined?
Alternatively, will this notation, from the second link, be supported?
/[\u3000-\u303F]|[\u3040-\u309F]|[\u30A0-\u30FF]|[\uFF00-\uFFEF]|[\u4E00-\u9FAF]|[\u2605-\u2606]|[\u2190-\u2195]|\u203B/g; 
Looking at this second one, would placing a | character make it so the first two sets of regexp in the previous comment can be combined as belonging to the same language?

**Comment by zersiax** [comment]
That is an affirmative. For people stumbling across this issue as well, the regexp you want for Japanese to have it read both Kanji as well as kana, is the following:
ja_ja:([一-龯])|([ぁ-んァ-ン])

I am not entirely sure if this will work with half-width and other edge cases, but should help out in the majority of cases.
